### ISSUE TITLE
Wiki Review

### ISSUE THREAD

**Issue by jmeyer90** [besonend/punchstopper#8]
1. MVP List:
* List the description and functionality beneath the "Hostin on Heroku" section.

2. Front-End Routes:
* 'project/id' should be 'project/:id'
* under 'project/:id' alter the description to describe what the page is showing.
* Under all Routes, you should state the main components that will be rendered: jobs list, search bar, description and contact info, etc.

3. Sample Sate:
* Separate the inner text of each object so that each key-value pair is on a new line.
* Rather than 'a,b,c' or bullet points, the keys for the objects in your front-end state should be the object's id. The id should be listed in the object as well.

**Comment by besonend** [comment]
done it
